<?php
/**
 * Task Export System
 * Generates downloadable files with all task data
 */

require_once __DIR__ . '/database/config.php';

// Check if we should generate the export
if (isset($_GET['export'])) {
    $format = $_GET['export'];
    
    try {
        // Get all tasks from database
        $connection = DatabaseConfig::getConnection();
        
        $query = "
            SELECT 
                t.*,
                rt.name as recurrency_type,
                CASE 
                    WHEN t.priority <= 10 THEN 'Critical'
                    WHEN t.priority <= 25 THEN 'High'
                    WHEN t.priority <= 50 THEN 'Medium'
                    WHEN t.priority <= 75 THEN 'Low'
                    ELSE 'Very Low'
                END as priority_label
            FROM tasks t
            LEFT JOIN recurrency_types rt ON t.recurrency_type_id = rt.id
            ORDER BY t.created_at DESC, t.priority ASC
        ";
        
        $stmt = $connection->prepare($query);
        $stmt->execute();
        $tasks = $stmt->fetchAll();
        
        if ($format === 'txt') {
            // Generate text file
            $filename = 'TaskManager_Export_' . date('Y-m-d_H-i-s') . '.txt';
            
            header('Content-Type: text/plain');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            
            echo "=".str_repeat("=", 78)."=\n";
            echo "                    TASK MANAGER - COMPLETE EXPORT\n";
            echo "                    Generated: " . date('Y-m-d H:i:s') . "\n";
            echo "=".str_repeat("=", 78)."=\n\n";
            
            // Summary
            $totalTasks = count($tasks);
            $pendingTasks = count(array_filter($tasks, function($t) { return $t['status'] === 'pending'; }));
            $completedTasks = count(array_filter($tasks, function($t) { return $t['status'] === 'completed'; }));
            $inProgressTasks = count(array_filter($tasks, function($t) { return $t['status'] === 'in_progress'; }));
            
            echo "SUMMARY:\n";
            echo "--------\n";
            echo "Total Tasks: $totalTasks\n";
            echo "Pending: $pendingTasks\n";
            echo "In Progress: $inProgressTasks\n";
            echo "Completed: $completedTasks\n\n";
            
            echo "DETAILED TASK LIST:\n";
            echo str_repeat("=", 80) . "\n\n";
            
            foreach ($tasks as $i => $task) {
                echo "Task #" . ($i + 1) . " (ID: {$task['id']})\n";
                echo str_repeat("-", 40) . "\n";
                echo "Title: " . ($task['title'] ?? 'N/A') . "\n";
                echo "Description: " . ($task['description'] ?? 'N/A') . "\n";
                echo "Priority: {$task['priority']} ({$task['priority_label']})\n";
                echo "Status: " . ucfirst($task['status']) . "\n";
                echo "Deadline: " . ($task['deadline'] ? date('Y-m-d H:i', strtotime($task['deadline'])) : 'Not set') . "\n";
                echo "Planned Date: " . ($task['planned_date'] ? date('Y-m-d H:i', strtotime($task['planned_date'])) : 'Not set') . "\n";
                echo "Recurrency: " . ($task['recurrency_type'] ?? 'None') . "\n";
                echo "Created: " . date('Y-m-d H:i', strtotime($task['created_at'])) . "\n";
                echo "Updated: " . date('Y-m-d H:i', strtotime($task['updated_at'])) . "\n";
                if ($task['completed_at']) {
                    echo "Completed: " . date('Y-m-d H:i', strtotime($task['completed_at'])) . "\n";
                }
                echo "\n" . str_repeat("=", 80) . "\n\n";
            }
            
            echo "End of Export - Generated by Task Manager System\n";
            exit;
            
        } elseif ($format === 'csv') {
            // Generate CSV file
            $filename = 'TaskManager_Export_' . date('Y-m-d_H-i-s') . '.csv';
            
            header('Content-Type: text/csv');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            
            $output = fopen('php://output', 'w');
            
            // CSV Headers
            fputcsv($output, [
                'ID', 'Title', 'Description', 'Priority', 'Priority Label', 'Status',
                'Deadline', 'Planned Date', 'Recurrency Type', 'Created At', 
                'Updated At', 'Completed At'
            ]);
            
            // CSV Data
            foreach ($tasks as $task) {
                fputcsv($output, [
                    $task['id'],
                    $task['title'] ?? '',
                    $task['description'] ?? '',
                    $task['priority'],
                    $task['priority_label'],
                    ucfirst($task['status']),
                    $task['deadline'] ?? '',
                    $task['planned_date'] ?? '',
                    $task['recurrency_type'] ?? 'None',
                    $task['created_at'],
                    $task['updated_at'],
                    $task['completed_at'] ?? ''
                ]);
            }
            
            fclose($output);
            exit;
        }
        
    } catch (Exception $e) {
        die('Error generating export: ' . htmlspecialchars($e->getMessage()));
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Export Tasks</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .export-btn {
            background-color: #dc3545;
            color: white;
            padding: 15px 30px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
            margin: 10px 10px 10px 0;
        }
        .export-btn:hover {
            background-color: #c82333;
        }
        .export-btn.csv {
            background-color: #28a745;
        }
        .export-btn.csv:hover {
            background-color: #218838;
        }
        .export-btn.txt {
            background-color: #007bff;
        }
        .export-btn.txt:hover {
            background-color: #0056b3;
        }
        .info {
            background-color: #e7f3ff;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
        .back-link {
            color: #007bff;
            text-decoration: none;
            margin-right: 20px;
        }
        .back-link:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📄 Export Tasks</h1>
        
        <div class="info">
            <h3>📋 What will be included:</h3>
            <ul>
                <li><strong>All tasks</strong> - Complete database export</li>
                <li><strong>Task details</strong> - ID, title, description, priority, status</li>
                <li><strong>Dates</strong> - Creation date, deadline, planned date</li>
                <li><strong>Summary statistics</strong> - Total, pending, completed tasks</li>
                <li><strong>Generation timestamp</strong> - For historical comparison</li>
            </ul>
            
            <p><strong>Perfect for:</strong> Backup purposes, historical comparison, offline review, sharing task lists</p>
        </div>
        
        <h3>📥 Choose Export Format:</h3>
        
        <a href="?export=txt" class="export-btn txt">📄 Text File (.txt)</a>
        <a href="?export=csv" class="export-btn csv">📊 Spreadsheet (.csv)</a>
        
        <div style="margin-top: 30px;">
            <a href="index.php" class="back-link">← Back to Task Manager</a>
            <a href="test_config.php" class="back-link">🔧 Configuration Test</a>
        </div>
    </div>
</body>
</html>